################################################################################
## succession_traits: supp_plots.R
## Builds all supplementary figures from pre-computed analysis outputs.
## Reads .rds files from tables/ and writes figures to figures/supplementary/.
##
## Figures produced:
##   S1: PCA scree + varimax contributions      (pca/)
##   S2: Environmental strata distributions     (feature value densities per high/low stratum)
##   S3: SHAP beeswarm plots                    (shap_beeswarm/)
##   S4: SHAP dependence plots                  (shap_dependence/)
##   S5: PDP fit lines                          (pdp/)
##   S6: Full VEcv trajectories (all 9 traits)  (vecv/)
##   S7: Full ΔVEcv per trait                   (vecv/)
##   S8: Env/succ ratio lollipop                (alternative RQ1 view)
##
## Author: M. Weiss @ Maynard Lab UCL / ETH Zürich
################################################################################

rm(list = ls())

# ── Libraries ─────────────────────────────────────────────────────────────────
library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(ggh4x)
library(cowplot)
library(psych)

source("scripts/plot_theme.R")
source("scripts/functions.R")

# ── Output directories ────────────────────────────────────────────────────────
DIR_SUPP     <- "figures/supplementary"
DIR_PCA      <- file.path(DIR_SUPP, "pca")
DIR_BEESWARM <- file.path(DIR_SUPP, "shap_beeswarm")
DIR_DEPEND   <- file.path(DIR_SUPP, "shap_dependence")
DIR_PDP      <- file.path(DIR_SUPP, "pdp")
DIR_VECV     <- file.path(DIR_SUPP, "vecv")

walk(c(DIR_SUPP, DIR_PCA, DIR_BEESWARM, DIR_DEPEND, DIR_PDP, DIR_VECV),
		 ~ dir.create(.x, recursive = TRUE, showWarnings = FALSE))

# ── Load tables ───────────────────────────────────────────────────────────────
shap_values     <- read_rds("tables/shap_values.rds")
shap_per_var    <- read_rds("tables/shap_per_var.rds")
shap_importance <- read_rds("tables/shap_importance.rds")
pdp_raw         <- read_rds("tables/pdp_raw.rds")
vecv_raw        <- read_rds("tables/vecv_raw.rds")
vecv_summary    <- read_rds("tables/vecv_summary.rds")
vecv_divergence <- read_rds("tables/vecv_divergence.rds")
data_clean      <- read_rds("data_processed/fia_traits_clean.rds")

# ── Analytical constants ──────────────────────────────────────────────────────
ENV_VARS   <- c("temp_pc", "soil_pc", "rain_pc", "elevation", "soil_ph")
LEAF_TYPES <- c("broadleaf", "coniferous")
TRAITS     <- names(TRAIT_LABELS)
COVARIATES <- c("standage", "temp_pc", "soil_pc", "rain_pc", "elevation", "soil_ph")

# Convenience wrapper for supplementary figures
save_supp <- function(plot, filename, dir = DIR_SUPP,
											width = 180, height = 140, dpi = 300) {
	save_fig(plot, filename, dir = dir,
					 width = width, height = height, dpi = dpi)
}


# ══════════════════════════════════════════════════════════════════════════════
# S1 — PCA scree plot and varimax contribution plots
# ══════════════════════════════════════════════════════════════════════════════
# Already generated by 02_environment_pca.R and saved to figures/supplementary/pca/
# Re-generate here for consistency with current theme if needed.

message("S1: PCA figure — already in figures/supplementary/pca/. Skipping rebuild.")
message("    To rebuild, re-run 02_environment_pca.R with updated PATH_PLOTS.")


# ══════════════════════════════════════════════════════════════════════════════
# S2 — Environmental strata distributions
# ══════════════════════════════════════════════════════════════════════════════
# Shows the distribution of each environmental predictor split into high/low
# quantile strata, providing numerical context for the stratification used
# in the PDP and VEcv analyses. One panel per predictor, split by leaf type.

message("Building S2 (environmental strata distributions)...")

# Derive leaf type
data_strata <- data_clean %>%
	mutate(
		leaf_type = case_when(
			biome_boreal_forests_or_taiga    == 1 |
				biome_temperate_conifer_forests  == 1 ~ "Coniferous",
			biome_temperate_broadleaf_forests == 1 |
				biome_mediterranean_woodlands    == 1 ~ "Broadleaf",
			TRUE ~ NA_character_
		)
	) %>%
	filter(!is.na(leaf_type))

# Compute quantile thresholds per leaf type and variable
strata_data <- map_dfr(LEAF_TYPES, function(lt) {
	df_lt <- data_strata %>% filter(leaf_type == str_to_title(lt))
	map_dfr(ENV_VARS, function(env) {
		qs <- quantile(df_lt[[env]], c(0.25, 0.75), na.rm = TRUE)
		df_lt %>%
			mutate(
				variable       = env,
				variable_label = recode(env, !!!ENV_LABELS),
				feature_value  = .data[[env]],
				stratum = case_when(
					.data[[env]] <= qs[1] ~ "Lower 25%",
					.data[[env]] >= qs[2] ~ "Upper 25%",
					TRUE                  ~ "Middle 50%"
				)
			) %>%
			dplyr::select(leaf_type, variable, variable_label,
										feature_value, stratum)
	})
})

# Colour scale consistent with strata maps in Figure 1
COLS_STRATA_SUPP <- c(
	"Lower 25%"  = "#4575B4",
	"Middle 50%" = "grey70",
	"Upper 25%"  = "#D73027"
)

s2 <- strata_data %>%
	filter(stratum != "Middle 50%") %>%
	mutate(
		variable_label = factor(variable_label, levels = ENV_LABELS),
		stratum        = factor(stratum, levels = c("Lower 25%", "Upper 25%"))
	) %>%
	ggplot(aes(x = feature_value, fill = stratum, colour = stratum)) +
	geom_density(alpha = 0.4, linewidth = 0.5) +
	geom_vline(xintercept = 0, linetype = "dashed",
						 colour = "grey50", linewidth = 0.3) +
	facet_grid(leaf_type ~ variable_label, scales = "free") +
	scale_fill_manual(
		values = COLS_STRATA_SUPP[c("Lower 25%", "Upper 25%")],
		name   = "Stratum"
	) +
	scale_colour_manual(
		values = COLS_STRATA_SUPP[c("Lower 25%", "Upper 25%")],
		name   = "Stratum"
	) +
	labs(
		x = "Feature value (z-scored or raw PC score)",
		y = "Density"
	) +
	theme_succession(base_size = 9) +
	theme(legend.position = "bottom")

save_supp(s2, "S2_strata_distributions.png",
					dir = DIR_SUPP, width = 220, height = 120)


# ══════════════════════════════════════════════════════════════════════════════
# S3 — SHAP beeswarm plots (one per trait × leaf type)
# ══════════════════════════════════════════════════════════════════════════════
# Already generated by 04_shap.R and saved to figures/supplementary/shap_beeswarm/
# Re-generate here with updated theme.

message("Building S3 (SHAP beeswarm plots)...")

MAX_POINTS <- 5000L

for (lt in LEAF_TYPES) {
	for (tr in TRAITS) {
		
		var_order <- shap_values %>%
			filter(trait == tr, leaf_type == lt) %>%
			group_by(variable) %>%
			summarise(mean_abs = mean(abs(shap_value), na.rm = TRUE),
								.groups = "drop") %>%
			arrange(mean_abs) %>%
			pull(variable)
		
		df_sub <- shap_values %>%
			filter(trait == tr, leaf_type == lt) %>%
			group_by(variable) %>%
			mutate(value_col = symmetric_scale(feature_value)) %>%
			ungroup() %>%
			mutate(variable = factor(variable, levels = var_order)) %>%
			{ if (nrow(.) > MAX_POINTS) slice_sample(., n = MAX_POINTS) else . }
		
		p_bee <- ggplot(df_sub,
										aes(x = variable, y = shap_value, colour = value_col)) +
			ggbeeswarm::geom_quasirandom(alpha = 0.35, size = 0.8) +
			geom_hline(yintercept = 0, linetype = "dashed",
								 colour = "grey50", linewidth = 0.3) +
			coord_flip() +
			scale_x_discrete(labels = ALL_PREDICTOR_LABELS) +
			scale_colour_viridis_c(
				name   = "Feature value",
				limits = c(-1, 1),
				breaks = c(-1, 0, 1),
				labels = c("Low", "Mid", "High")
			) +
			labs(
				x = NULL,
				y = "SHAP value",
				subtitle = paste0(TRAIT_LABELS[[tr]], " — ", str_to_title(lt))
			) +
			theme_succession(base_size = 9) +
			theme(
				panel.grid.major.y = element_blank(),
				axis.text.y        = element_text(size = 8),
				legend.position    = "right",
				legend.key.height  = unit(3, "mm")
			)
		
		save_supp(p_bee,
							sprintf("beeswarm_%s_%s.png", tr, lt),
							dir    = DIR_BEESWARM,
							width  = 120, height = 90)
	}
}
message("  ✓ S3 beeswarm plots saved")


# ══════════════════════════════════════════════════════════════════════════════
# S4 — SHAP dependence plots (one per variable × trait)
# ══════════════════════════════════════════════════════════════════════════════

message("Building S4 (SHAP dependence plots)...")

for (tr in TRAITS) {
	for (var in COVARIATES) {
		
		p_dep <- shap_values %>%
			filter(trait == tr, variable == var) %>%
			mutate(leaf_type = str_to_title(leaf_type)) %>%
			ggplot(aes(x = feature_value, y = shap_value,
								 colour = leaf_type, shape = leaf_type)) +
			geom_point(alpha = 0.2, size = 0.9) +
			geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"),
									se = FALSE, linewidth = 0.8) +
			geom_hline(yintercept = 0, linetype = "dashed",
								 colour = "grey50", linewidth = 0.3) +
			scale_colour_manual(values = COLS_LEAFTYPE, name = NULL) +
			scale_shape_manual(values = SHAPES_LEAFTYPE, name = NULL) +
			labs(
				x        = ALL_PREDICTOR_LABELS[[var]],
				y        = "SHAP value",
				subtitle = TRAIT_LABELS[[tr]]
			) +
			theme_succession(base_size = 9) +
			theme(legend.position = "bottom")
		
		save_supp(p_dep,
							sprintf("dependence_%s_%s.png", var, tr),
							dir   = DIR_DEPEND,
							width = 100, height = 85)
	}
}
message("  ✓ S4 dependence plots saved")


# ══════════════════════════════════════════════════════════════════════════════
# S5 — PDP fit lines (raw bootstrap curves)
# ══════════════════════════════════════════════════════════════════════════════
# Already generated by 05_pdp.R. Rebuild here with updated theme.

message("Building S5 (PDP fit lines)...")

s5 <- pdp_raw %>%
	mutate(
		leaf_type      = str_to_title(leaf_type),
		trait_label    = recode(trait,    !!!TRAIT_LABELS),
		variable_label = recode(variable, !!!ENV_LABELS),
		trait_label    = factor(trait_label,    levels = TRAIT_LABELS),
		variable_label = factor(variable_label, levels = ENV_LABELS)
	) %>%
	ggplot(aes(x = standage, y = yhat)) +
	geom_point(aes(fill = group), alpha = 0.03, size = 0.3,
						 shape = 21, stroke = 0.1, colour = "black") +
	geom_smooth(aes(colour = group), method = "lm",
							se = FALSE, linewidth = 0.5, formula = y ~ x) +
	ggh4x::facet_nested(
		rows = vars(leaf_type, trait_label),
		cols = vars(variable_label),
		scales = "free_y"
	) +
	scale_fill_manual(
		values = c("low" = "lightcyan", "high" = "lightcoral"),
		labels = c("low" = "Lower quantile", "high" = "Upper quantile"),
		name   = NULL
	) +
	scale_colour_manual(
		values = c("low" = "navy", "high" = "darkred"),
		labels = c("low" = "Lower quantile", "high" = "Upper quantile"),
		name   = NULL
	) +
	labs(x = LAB_STANDAGE, y = "Predicted trait expression") +
	theme_succession(base_size = 7) +
	theme(legend.position = "top")

save_supp(s5, "S5_pdp_lines.png",
					dir    = DIR_PDP,
					width  = 260, height = 360)


# ══════════════════════════════════════════════════════════════════════════════
# S6 — Full VEcv trajectories (all 9 traits)
# ══════════════════════════════════════════════════════════════════════════════

message("Building S6 (full VEcv trajectories)...")

vecv_avg_full <- vecv_raw %>%
	group_by(trait, trait_label, leaf_type, env_group,
					 standage_bin, standage_mid, repeat_id) %>%
	summarise(VEcv = mean(VEcv, na.rm = TRUE), .groups = "drop") %>%
	group_by(trait, trait_label, leaf_type, env_group,
					 standage_bin, standage_mid) %>%
	summarise(
		VEcv_med = median(VEcv, na.rm = TRUE),
		VEcv_lwr = quantile(VEcv, 0.025, na.rm = TRUE),
		VEcv_upr = quantile(VEcv, 0.975, na.rm = TRUE),
		.groups  = "drop"
	) %>%
	mutate(
		env_group   = factor(env_group,
												 levels = c("low", "high"),
												 labels = c("Lower environmental quantile",
												 					 "Upper environmental quantile")),
		leaf_type   = str_to_title(leaf_type),
		trait_label = factor(trait_label, levels = TRAIT_LABELS)
	)

s6 <- ggplot(vecv_avg_full,
						 aes(x = standage_mid, colour = env_group, fill = env_group)) +
	geom_ribbon(aes(ymin = VEcv_lwr, ymax = VEcv_upr),
							alpha = 0.2, colour = NA) +
	geom_line(aes(y = VEcv_med), linewidth = 0.7) +
	geom_hline(yintercept = 0, linetype = "dashed",
						 colour = "grey50", linewidth = 0.3) +
	facet_grid(leaf_type ~ trait_label, scales = "free_y") +
	scale_colour_manual(values = COLS_ENVGROUP, name = NULL) +
	scale_fill_manual(  values = COLS_ENVGROUP, name = NULL) +
	scale_x_continuous(breaks = c(0, 50, 100, 150)) +
	scale_y_continuous(limits = c(0, NA)) +
	labs(x = LAB_STANDAGE, y = LAB_VECV) +
	theme_succession(base_size = 8) +
	theme(legend.position = "top",
				strip.text = element_text(face = "bold", size = 7))

save_supp(s6, "S6_vecv_full.png",
					dir    = DIR_VECV,
					width  = 260, height = 140)


# ══════════════════════════════════════════════════════════════════════════════
# S7 — Full ΔVEcv per trait × environmental variable
# ══════════════════════════════════════════════════════════════════════════════

message("Building S7 (full ΔVEcv per trait)...")

s7 <- vecv_divergence %>%
	filter(!is.na(delta_med)) %>%
	mutate(
		leaf_type      = str_to_title(leaf_type),
		trait_label    = factor(trait_label,    levels = TRAIT_LABELS),
		variable_label = factor(variable_label, levels = ENV_LABELS)
	) %>%
	ggplot(aes(x = standage_mid, y = delta_med,
						 colour = variable_label, fill = variable_label)) +
	geom_ribbon(aes(ymin = delta_lwr, ymax = delta_upr),
							alpha = 0.15, colour = NA) +
	geom_line(linewidth = 0.6) +
	geom_hline(yintercept = 0, linetype = "dashed",
						 colour = "grey40", linewidth = 0.35) +
	facet_grid(leaf_type ~ trait_label, scales = "free_y") +
	scale_colour_manual(values = COLS_ENV, name = NULL) +
	scale_fill_manual(  values = COLS_ENV, name = NULL) +
	scale_x_continuous(breaks = c(0, 50, 100, 150)) +
	labs(
		x = LAB_STANDAGE,
		y = LAB_DELTA_VECV
	) +
	theme_succession(base_size = 8) +
	theme(
		legend.position = "bottom",
		strip.text      = element_text(face = "bold", size = 7)
	)

save_supp(s7, "S7_vecv_divergence_full.png",
					dir    = DIR_VECV,
					width  = 260, height = 140)


# ══════════════════════════════════════════════════════════════════════════════
# S8 — Environmental / successional importance ratio lollipop
# ══════════════════════════════════════════════════════════════════════════════
# Alternative view of RQ1 showing the ratio directly on a log scale.
# Complements Figure 2 (stacked bar) by showing the magnitude of dominance.

message("Building S8 (env/succ ratio lollipop)...")

s8 <- shap_importance %>%
	mutate(
		trait_label = factor(
			trait_label,
			levels = shap_importance %>%
				group_by(trait_label) %>%
				summarise(m = mean(env_succ_ratio), .groups = "drop") %>%
				arrange(m) %>%
				pull(trait_label)
		),
		leaf_type = str_to_title(leaf_type)
	) %>%
	ggplot(aes(x = env_succ_ratio, y = trait_label, colour = leaf_type)) +
	geom_vline(xintercept = 1, linetype = "dashed",
						 colour = "grey50", linewidth = 0.4) +
	geom_segment(aes(x = 1, xend = env_succ_ratio,
									 y = trait_label, yend = trait_label),
							 linewidth = 0.6, alpha = 0.5) +
	geom_point(size = 3.5) +
	scale_colour_manual(values = COLS_LEAFTYPE, name = NULL) +
	scale_x_continuous(
		trans  = "log2",
		breaks = c(0.5, 1, 2, 5, 10, 20, 30),
		labels = function(x) paste0(x, "\u00d7")
	) +
	facet_wrap(~ leaf_type, ncol = 2) +
	labs(
		x = LAB_RATIO,
		y = NULL
	) +
	theme_succession(base_size = 10) +
	theme(
		legend.position    = "none",
		panel.grid.major.y = element_blank()
	)

save_supp(s8, "S8_ratio_lollipop.png",
					dir    = DIR_SUPP,
					width  = 180, height = 120)


# ══════════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════════

message("\n── supp_plots.R complete ───────────────────────────────────────────")
message("Supplementary figures saved to figures/supplementary/:")
list.files(DIR_SUPP, recursive = TRUE) %>%
	str_subset("\\.png$") %>%
	walk(~ message(sprintf("  %s", .x)))